config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homes#top"
  get "/contact", to: "contacts#new"
  post "contact/confirm", to: "contacts#confirm"
  post "contact/back", to: "contacts#back"
  post "/contact", to: "contacts#create"
  get "/question", to: "homes#question"
  post "/diaries/search", to: "diaries#search"
  get "/diaries/former_comment", to: "diaries#former_comment"
  post "/twitter_id", to: "diaries#twitter_id"
  resources :contacts, only: [:new, :create]
  resources :users
  resources :diaries
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def new
    @diary = current_user.diaries.find_or_initialize_by(date: Date.today)
    @lhob_num = current_user.past_lhob
    lhob_date = Date.today - @lhob_num.day
    @lhob = current_user.diaries.find_or_initialize_by(date: lhob_date)
    @lhib_num = current_user.past_lhib
    lhib_date = Date.today - @lhib_num.day
    @lhib = current_user.diaries.find_or_initialize_by(date: lhib_date)
    @rhib_num = current_user.past_rhib
    rhib_date = Date.today - @rhib_num.day
    @rhib = current_user.diaries.find_or_initialize_by(date: rhib_date)
    @rhob_num = current_user.past_rhob
    rhob_date = Date.today - @rhob_num.day
    @rhob = current_user.diaries.find_or_initialize_by(date: rhob_date)
    @twitter_id = current_user.twitter_id
    @twitter_url = current_user.twitter_url
  end

  def create
    current_user.diaries.create!(diary_params)
    redirect_to new_diary_path
  end

  def search
    @choose_date = params[:data][:date]
    @choose_diary = current_user.diaries.find_or_initialize_by(date: @choose_date)
    render json: @choose_diary
  end

  def former_comment
    @prev_position = params[:data][:position]
    @prev_date = params[:data][:date]
    current_user.send("past_#{@prev_position}=", @prev_date)
    current_user.save
    former_date = Date.today - @prev_date.to_i
    @choose_comment = current_user.diaries.find_or_initialize_by(date: former_date)
    render json: @choose_comment
  end

  def update
    current_user.diaries.update(diary_params)
    redirect_to new_diary_path
  end

  def twitter_id
    options = Selenium::WebDriver::Chrome::Options.new
    options.add_argument("--headless")
    driver = Selenium::WebDriver.for :chrome, options: options
    driver.navigate.to "https://publish.twitter.com/"
    element1 = driver.find_element(:id, "configuration-query")
    element1.send_keys params[:twitter_id].to_s
    begin
      element1.submit
      sleep 2
      element2 = driver.find_element(:class, "WidgetsSelector-item")
      element2.click
      sleep 2
      element3 = driver.find_element(:class, "EmbedCode-container")
      twitter_data = element3.text
      twitter_split = twitter_data.split("href=")
      twitter_url = twitter_split[1].split(">Tweets by")
      twitter_name = twitter_url[1].split("</a>")
      twitter_url = twitter_url[0]
      twitter_id = twitter_name[0]
      current_user.update!(twitter_id: twitter_id, twitter_url: twitter_url)
      redirect_to new_diary_path
    rescue
      redirect_to new_diary_path, flash: { danger: "IDが有効ではなかったため、登録出来ませんでした。" }
    end
  end

  private

  def diary_params
    params.require(:diary).permit(:title, :comment, :date, user_id: current_user.id)
  end
end

app/views/diaries/edit.html.erb
<div class="container-fluid" style="max-width: 1280px">
  <h3 class="pt-3 text-primary col-2">Calendar</h3>
  <input type="text" id="calendar" class="initial-font mb-3" form="diary-form" name="diary[date]">
  <div class="row">
    <div class="col-md-3 col-12">
      <div class="dropdown">
        <div class="ext-dark border p-1 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Former Day
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to "1 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "3 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "7 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "30 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "90 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "180 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "365 day ago", "/#", class: "dropdown-item" %>
        </div>
      </div>
      <!-- Button trigger modal -->
      <div class="text-dark border p-3" data-toggle="modal" data-target="#exampleModalLong">
        Launch demo modal
        Launch demo modal
      </div>
      <!-- Modal -->
      <div class="modal fade bd-example-modal-lg" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-12">
      <div class="dropdown">
        <div class="ext-dark border p-1 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Former Day
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to "1 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "3 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "7 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "30 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "90 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "180 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "365 day ago", "/#", class: "dropdown-item" %>
        </div>
      </div>
      <!-- Button trigger modal -->
      <div class="text-dark border p-3" data-toggle="modal" data-target="#exampleModalLong">
        Launch demo modal
        Launch demo modal
      </div>
      <!-- Modal -->
      <div class="modal fade bd-example-modal-lg" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-12">
      <div class="dropdown">
        <div class="ext-dark border p-1 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Former Day
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to "1 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "3 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "7 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "30 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "90 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "180 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "365 day ago", "/#", class: "dropdown-item" %>
        </div>
      </div>
      <!-- Button trigger modal -->
      <div class="text-dark border p-3" data-toggle="modal" data-target="#exampleModalLong">
        Launch demo modal
        Launch demo modal
      </div>
      <!-- Modal -->
      <div class="modal fade bd-example-modal-lg" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-12">
      <div class="dropdown">
        <div class="ext-dark border p-1 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Former Day
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to "1 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "3 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "7 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "30 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "90 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "180 day ago", "/#", class: "dropdown-item" %>
          <%= link_to "365 day ago", "/#", class: "dropdown-item" %>
        </div>
      </div>
      <!-- Button trigger modal -->
      <div class="text-dark border p-3" data-toggle="modal" data-target="#exampleModalLong">
        Launch demo modal
        Launch demo modal
      </div>
      <!-- Modal -->
      <div class="modal fade bd-example-modal-lg" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-md-3 col-12">
      <%= form_with model: @Twitter, local: true do |form| %>
        <div class="form-group" >
          <%= form.label :title, "Twitter id" %>
          <%= form.text_field :title, required: true, class: "form-control" %>
        </div>
      <% end %>
      <a class="twitter-timeline" data-lang="ja" data-height="700" href="https://twitter.com/take18k_tech?ref_src=twsrc%5Etfw">Tweets by take18k_tech</a>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
    <div class="col-md-9 col-12">
      <%= form_with model: @diary, local: true, id: "diary-form" do |form| %>
        <div class="form-group" >
          <%= form.label :title, "Diary Title" %>
          <%= form.text_field :title, required: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :comment, "Diary Comment" %>
          <%= form.text_area :comment, required: true, class: "form-control", rows: 25 %>
        </div>
        <div class="text-right">
          <%= form.submit "Save", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/diaries/new.html.erb
<div class="container-fluid px-5" style="max-width: 1920px">
  <h3 class="pt-3 text-primary col-2">Calendar</h3>
  <input type="text" id="calendar" class="initial-font mb-3" form="diary-form" name="diary[date]">
  <div class="row">
    <div class="col-md-3 col-12 former-day">
      <div class="dropdown">
        <div class="ext-dark border p-1 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "#{@lhob_num} day ago" %>
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% [1,3,7,15,30,60,90,120,180,365].each do |num| %>
            <div class="dropdown-item" value="<%= num %> day ago" data-position="lhob" data-former="<%= num %>"><%= num %> day ago</div>
          <% end %>
        </div>
      </div>
      <!-- Button trigger modal -->
      <div class="text-dark border p-1" data-toggle="modal" data-target="#modal-lhob">
        <p class="prev-text former-text-lhob mb-0"><%= @lhob.comment %></p>
      </div>
      <!-- Modal -->
      <div class="modal fade bd-example-modal-lg" id="modal-lhob" tabindex="-1" role="dialog" aria-labelledby="modal-lhobTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modal-lhobTitle"><%= @lhob.title %></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" id="former-day-comment-lhob">
              <%= @lhob.comment %>
            </div>
            <div class="modal-footer">
              <%# <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button> %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-12 former-day">
      <div class="dropdown">
        <div class="ext-dark border p-1 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "#{@lhib_num} day ago" %>
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% [1,3,7,15,30,60,90,120,180,365].each do |num| %>
            <div class="dropdown-item" value="<%= num %> day ago" data-position="lhib" data-former="<%= num %>"><%= num %> day ago</div>
          <% end %>
        </div>
      </div>
      <!-- Button trigger modal -->
      <div class="text-dark border p-1" data-toggle="modal" data-target="#modal-lhib">
        <p class="prev-text former-text-lhib mb-0"><%= @lhib.comment %></p>
      </div>
      <!-- Modal -->
      <div class="modal fade bd-example-modal-lg" id="modal-lhib" tabindex="-1" role="dialog" aria-labelledby="modal-lhibTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modal-lhibTitle"><%= @lhib.title %></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" id="former-day-comment-lhib">
              <%= @lhib.comment %>
            </div>
            <div class="modal-footer">
              <%# <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button> %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-12 former-day">
      <div class="dropdown">
        <div class="ext-dark border p-1 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "#{@rhib_num} day ago" %>
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% [1,3,7,15,30,60,90,120,180,365].each do |num| %>
            <div class="dropdown-item" value="<%= num %> day ago" data-position="rhib" data-former="<%= num %>"><%= num %> day ago</div>
          <% end %>
        </div>
      </div>
      <!-- Button trigger modal -->
      <div class="text-dark border p-1" data-toggle="modal" data-target="#modal-rhib">
        <p class="prev-text former-text-rhib mb-0"><%= @rhib.comment %></p>
      </div>
      <!-- Modal -->
      <div class="modal fade bd-example-modal-lg" id="modal-rhib" tabindex="-1" role="dialog" aria-labelledby="modal-rhibTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modal-rhibTitle"><%= @rhib.title %></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" id="former-day-comment-rhib">
              <%= @rhib.comment %>
            </div>
            <div class="modal-footer">
              <%# <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button> %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-12 former-day">
      <div class="dropdown">
        <div class="ext-dark border p-1 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "#{@rhob_num} day ago" %>
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% [1,3,7,15,30,60,90,120,180,365].each do |num| %>
            <div class="dropdown-item" value="<%= num %> day ago" data-position="rhob" data-former="<%= num %>"><%= num %> day ago</div>
          <% end %>
        </div>
      </div>
      <!-- Button trigger modal -->
      <div class="text-dark border p-1" data-toggle="modal" data-target="#modal-rhob">
        <p class="prev-text former-text-rhob mb-0"><%= @rhob.comment %></p>
      </div>
      <!-- Modal -->
      <div class="modal fade bd-example-modal-lg" id="modal-rhob" tabindex="-1" role="dialog" aria-labelledby="modal-rhobTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modal-rhobTitle"><%= @rhob.title %></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" id="former-day-comment-rhob">
              <%= @rhob.comment %>
            </div>
            <div class="modal-footer">
              <%# <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button> %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-md-3 col-12">
      <%= form_with model: @twitter, url: twitter_id_path, local: true do |form| %>
        <%= form.label :twitter_id, "Twitter id" %>
        <div class="form-row">
          <div class="col-8">
            <%= form.text_field :twitter_id, required: true, class: "form-control" %>
          </div>
          <div class="col-4">
            <%= form.submit "Search", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
      <div class="twitter_height">
        <a class="twitter-timeline" href=<%= @twitter_url %>>Tweets by<%= @twitter_id %></a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
    </div>
    <div class="col-md-9 col-12">
      <%= form_with model: @diary, local: true, id: "diary-form" do |form| %>
        <div class="form-group" >
          <%= form.label :title, "Diary Title" %>
          <%= form.text_field :title, required: true, class: "form-control", id: "diary-title" %>
        </div>
        <div class="form-group">
          <%= form.label :comment, "Diary Comment" %>
          <%= form.text_area :comment, required: true, class: "form-control", id: "diary-comment", rows: 25 %>
        </div>
        <div class="text-right">
          <%= form.submit "Save", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>