config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homes#top"
  get "/contact", to: "contacts#new"
  post "contact/confirm", to: "contacts#confirm"
  post "contact/back", to: "contacts#back"
  post "/contact", to: "contacts#create"
  get "/question", to: "homes#question"
  post "/diaries/search", to: "diaries#search"
  get "/diaries/former_comment", to: "diaries#former_comment"
  post "/twitter_id", to: "diaries#twitter_id"
  resources :contacts, only: [:new, :create]
  resources :users
  resources :diaries
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :contact_params, except: :new

  def new
    @contact = Contact.new
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  def create
    contact = Contact.create!(contact_params)
    if contact.save
      ContactMailer.send_customer_mail(contact).deliver_now
      ContactMailer.send_developer_mail(contact).deliver_now
      flash.now[:notice] = "送信完了しました。"
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:last_name, :first_name, :email, :inquiry)
  end
end

app/views/contacts/confirm.html.erb
<div class="container-login py-0">
  <div class="title">
    <span><%= image_tag 'f_f_business_12_s512_f_business_12_0.png' %></span>
    <h3><strong>Contact us</strong></h3>
  </div>
  <div class="row mt-4 text-center">
    <div class="confirm col-md-4 col-12 p-1">
      <p class="other-confirm">1.Input</p>
    </div>
    <div class="confirm col-md-4 col-12 p-1">
      <p class="current">2.Confirm</p>
    </div>
    <div class="confirm col-md-4 col-12 p-1">
      <p class="other-confirm">3.Complete</p>
    </div>
  </div>
  <p class="text-center text-white bg-info p-2 col-12">記入内容に間違いがないかご確認下さい</p>
  <div class="form-group">
    <label for="exampleInputEmail1">Last name</label>
    <input type="name" class="form-control bg-white" id="exampleInputEmail1" value="<%= @contact.last_name %>" disabled>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">First name</label>
    <input type="name" class="form-control bg-white" id="exampleInputEmail1" value="<%= @contact.first_name %>" disabled>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
    <input type="email" class="form-control bg-white" id="exampleInputEmail1" value="<%= @contact.email %>" disabled>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Inquiry</label>
    <textarea class="form-control bg-white" id="exampleInputEmail1" rows="9" disabled><%= @contact.inquiry %>
    </textarea>
  </div>
  <%= form_with model: @contact, url: contact_back_path, local: true do |form| %>
    <div class="form-group" >
      <%= form.hidden_field :last_name %>
    </div>
    <div class="form-group" >
      <%= form.hidden_field :first_name %>
    </div>
    <div class="form-group" >
      <%= form.hidden_field :email %>
    </div>
    <div class="form-group" >
      <%= form.hidden_field :inquiry %>
    </div>
    <div class="form-group" >
      <%= form.submit 'Back', class: 'btn btn-secondary' %>
    </div>
  <% end %>
  <%= form_with model: @contact, url: contacts_path, method: :post, local: true do |form| %>
    <div class="form-group" >
      <%= form.hidden_field :last_name%>
    </div>
    <div class="form-group" >
      <%= form.hidden_field :first_name %>
    </div>
    <div class="form-group" >
      <%= form.hidden_field :email %>
    </div>
    <div class="form-group" >
      <%= form.hidden_field :inquiry %>
    </div>
    <div class="form-group" >
      <%= form.submit 'Send', class: 'btn btn-primary' %>
    </div>
  <% end %>

app/views/contacts/create.html.erb
<div class="container-login">
  <div class="title">
    <span><%= image_tag 'f_f_event_3_s512_f_event_3_0.png' %></span>
    <h3><strong>Contact us</strong></h3>
  </div>
  <div class="row mt-4 text-center">
    <div class="confirm col-md-4 col-12 p-1">
      <p class="other-confirm">1.Input</p>
    </div>
    <div class="confirm col-md-4 col-12 p-1">
      <p class="other-confirm">2.Confirm</p>
    </div>
    <div class="confirm col-md-4 col-12 p-1">
      <p class="current">3.Complete</p>
    </div>
  </div>
  <div class="text-center text-white bg-info m-0 p-2 col-12">
    <p class="m-0">お問い合わせありがとう御座います。</p>
    <p class="m-0">改めて連絡を差し上げますのでしばらくお待ち下さい。</p>
  </div>
  <a href="/" class="btn btn-primary mt-4" >Return to top</a>

app/views/contacts/new.html.erb
<div class="container-login py-0">
  <div class="title">
    <span><%= image_tag 'f_f_business_12_s512_f_business_12_0.png' %></span>
    <h3><strong>Contact us</strong></h3>
  </div>
  <div class="row mt-4 text-center">
    <div class="confirm col-md-4 col-12 p-1">
      <p class="current">1.Input</p>
    </div>
    <div class="confirm col-md-4 col-12 p-1">
      <p class="other-confirm">2.Confirm</p>
    </div>
    <div class="confirm col-md-4 col-12 p-1">
      <p class="other-confirm">3.Complete</p>
    </div>
  </div>
  <%= form_with model: @contact, url: contact_confirm_path, local: true do |f| %>
    <div class="form-group" >
      <%= f.label :"Last name" %>
      <%= f.text_field :last_name, class: 'form-control mb-3', placeholder: "Last name", required: true %>
    </div>
    <div class="form-group" >
      <%= f.label :"First name" %>
      <%= f.text_field :first_name, class: 'form-control mb-3', placeholder: "First name", required: true %>
    </div>
    <div class="form-group">
      <%= f.label :"Email" %>
      <%= f.email_field :email, autocomplete: 'email', class: 'form-control', placeholder: "example@example.com", required: true %>
    </div>
    <div class="form-group">
      <%= f.label :"Inquiry" %>
      <%= f.text_area :inquiry, class: 'form-control', rows:9, required: true %>
    </div>
    <div class="form-group">
      <%= f.submit "Send", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>