config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homes#top"
  get "/contact", to: "contacts#new"
  post "contact/confirm", to: "contacts#confirm"
  post "contact/back", to: "contacts#back"
  post "/contact", to: "contacts#create"
  get "/question", to: "homes#question"
  post "/diaries/search", to: "diaries#search"
  get "/diaries/former_comment", to: "diaries#former_comment"
  post "/twitter_id", to: "diaries#twitter_id"
  resources :contacts, only: [:new, :create]
  resources :users
  resources :diaries
end

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light">
  <%= link_to "Diary GSE", root_path, class:"navbar-brand  text-white h1 pr-4 m-0", data: {"turbolinks"=>false} %>
  <div class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    <%# <span><%= image_tag 'f_f_health_37_s512_f_health_37_0.png'</span> %>
  </div>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, class:"nav-link text-white", method: :delete %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit", edit_user_registration_path, class:"nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Question", "/question", class:"nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", new_contact_path, class:"nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "New", new_diary_path, class:"nav-link text-white" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Create New", new_user_registration_path, class:"nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class:"nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Question", "/question", class:"nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", "/contact", class:"nav-link text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiaryForGse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="main-container">
      <% flash.each do |key, value| %>
        <p class="alert alert-<%= key %> text-center mb-0">
          <%= value %>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        </p>
      <% end %>
      <%= yield %>
      <div class="btn-group mt-2 mb-4" role="group" aria-label="actionButtons">
      </div>
      <footer class="bg-primary text-white text-center p-3 fixed-bottom">
        copyright - taichi nagasaka, 2020 All Rights Reserved.
      </footer>
    </div>
  </body>
</html>